-- Generated by scripts/generate_baseline_sql.py from monitorforge_core.models.
-- Do not hand-edit. Re-run the generator instead.

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS meta;

CREATE TYPE core.resolution_type AS ENUM ('30s', '1m', '5m', '15m', 'hourly', '8h', 'daily', 'other');

CREATE TYPE core.deployment_status AS ENUM ('active', 'inactive', 'maintenance', 'retired');

CREATE TABLE core.calculation_runs (
	calculation_run_id BIGSERIAL NOT NULL, 
	run_type TEXT NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	status TEXT NOT NULL, 
	formula_version TEXT, 
	notes TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (calculation_run_id)
);

CREATE INDEX calculation_runs_status_idx ON core.calculation_runs (status);
CREATE INDEX calculation_runs_started_at_idx ON core.calculation_runs (started_at DESC);

CREATE TABLE core.projects (
	project_id SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	code TEXT, 
	description TEXT, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	uuid UUID NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_by TEXT, 
	updated_by TEXT, 
	PRIMARY KEY (project_id), 
	UNIQUE (uuid)
);

CREATE INDEX ix_core_projects_is_active ON core.projects (is_active);
CREATE UNIQUE INDEX ix_core_projects_code ON core.projects (code);

CREATE TABLE core.sensors (
	sensor_id SERIAL NOT NULL, 
	model TEXT, 
	serial_number TEXT NOT NULL, 
	manufacturer TEXT, 
	variable_family TEXT, 
	lower_bound FLOAT, 
	upper_bound FLOAT, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	uuid UUID NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_by TEXT, 
	updated_by TEXT, 
	PRIMARY KEY (sensor_id), 
	CONSTRAINT bounds_order CHECK (lower_bound IS NULL OR upper_bound IS NULL OR lower_bound < upper_bound), 
	UNIQUE (uuid)
);

CREATE INDEX ix_core_sensors_variable_family ON core.sensors (variable_family);
CREATE UNIQUE INDEX ix_core_sensors_serial_number ON core.sensors (serial_number);
CREATE INDEX sensors_serial_idx ON core.sensors (serial_number);
CREATE INDEX sensors_family_idx ON core.sensors (variable_family);

CREATE TABLE core.uploads (
	upload_id BIGSERIAL NOT NULL, 
	filename TEXT NOT NULL, 
	uploaded_by TEXT, 
	uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	source_timezone TEXT NOT NULL, 
	rows_read INTEGER NOT NULL, 
	rows_inserted INTEGER NOT NULL, 
	duplicates_skipped INTEGER NOT NULL, 
	conflicts_skipped INTEGER NOT NULL, 
	invalid_rows INTEGER NOT NULL, 
	status TEXT NOT NULL, 
	message TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (upload_id)
);

CREATE INDEX uploads_uploaded_at_idx ON core.uploads (uploaded_at DESC);
CREATE INDEX uploads_status_idx ON core.uploads (status);
CREATE INDEX ix_core_uploads_uploaded_at ON core.uploads (uploaded_at);

CREATE TABLE meta.activity_types (
	activity_type_id SERIAL NOT NULL, 
	code TEXT NOT NULL, 
	name TEXT NOT NULL, 
	description TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	uuid UUID NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (activity_type_id), 
	UNIQUE (uuid)
);

CREATE UNIQUE INDEX ix_meta_activity_types_code ON meta.activity_types (code);

CREATE TABLE meta.quality_flags (
	flag_id SERIAL NOT NULL, 
	code TEXT NOT NULL, 
	description TEXT NOT NULL, 
	severity TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	uuid UUID NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (flag_id), 
	UNIQUE (uuid)
);

CREATE UNIQUE INDEX ix_meta_quality_flags_code ON meta.quality_flags (code);

CREATE TABLE meta.units (
	unit_id SERIAL NOT NULL, 
	code TEXT NOT NULL, 
	name TEXT NOT NULL, 
	dimension TEXT, 
	description TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	uuid UUID NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (unit_id), 
	UNIQUE (uuid)
);

CREATE UNIQUE INDEX ix_meta_units_code ON meta.units (code);

CREATE TABLE core.monitoring_areas (
	area_id SERIAL NOT NULL, 
	project_id INTEGER, 
	name TEXT NOT NULL, 
	code TEXT, 
	description TEXT, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	uuid UUID NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_by TEXT, 
	updated_by TEXT, 
	PRIMARY KEY (area_id), 
	FOREIGN KEY(project_id) REFERENCES core.projects (project_id), 
	UNIQUE (uuid)
);

CREATE UNIQUE INDEX ix_core_monitoring_areas_code ON core.monitoring_areas (code);
CREATE INDEX ix_core_monitoring_areas_is_active ON core.monitoring_areas (is_active);
CREATE INDEX monitoring_areas_code_idx ON core.monitoring_areas (code);
CREATE INDEX monitoring_areas_project_idx ON core.monitoring_areas (project_id);
CREATE INDEX monitoring_areas_active_idx ON core.monitoring_areas (is_active);
CREATE INDEX ix_core_monitoring_areas_project_id ON core.monitoring_areas (project_id);

CREATE TABLE core.variables (
	variable_id SERIAL NOT NULL, 
	name TEXT NOT NULL, 
	code TEXT NOT NULL, 
	unit_id INTEGER, 
	description TEXT, 
	min_value FLOAT, 
	max_value FLOAT, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	uuid UUID NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_by TEXT, 
	updated_by TEXT, 
	PRIMARY KEY (variable_id), 
	FOREIGN KEY(unit_id) REFERENCES meta.units (unit_id), 
	UNIQUE (uuid)
);

CREATE INDEX vars_code_idx ON core.variables (code);
CREATE INDEX ix_core_variables_unit_id ON core.variables (unit_id);
CREATE UNIQUE INDEX ix_core_variables_code ON core.variables (code);
CREATE INDEX vars_unit_idx ON core.variables (unit_id);

CREATE TABLE core.monitoring_stations (
	station_id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	area_id INTEGER, 
	name TEXT NOT NULL, 
	code TEXT NOT NULL, 
	latitude FLOAT, 
	longitude FLOAT, 
	elevation_m FLOAT, 
	timezone TEXT NOT NULL, 
	description TEXT, 
	station_type TEXT, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	uuid UUID NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_by TEXT, 
	updated_by TEXT, 
	PRIMARY KEY (station_id), 
	FOREIGN KEY(project_id) REFERENCES core.projects (project_id), 
	FOREIGN KEY(area_id) REFERENCES core.monitoring_areas (area_id), 
	UNIQUE (uuid)
);

CREATE INDEX ix_core_monitoring_stations_code ON core.monitoring_stations (code);
CREATE INDEX ix_core_monitoring_stations_project_id ON core.monitoring_stations (project_id);
CREATE INDEX monitoring_stations_area_idx ON core.monitoring_stations (area_id);
CREATE INDEX monitoring_stations_project_idx ON core.monitoring_stations (project_id);
CREATE INDEX ix_core_monitoring_stations_is_active ON core.monitoring_stations (is_active);
CREATE INDEX ix_core_monitoring_stations_area_id ON core.monitoring_stations (area_id);
CREATE INDEX monitoring_stations_code_idx ON core.monitoring_stations (code);
CREATE INDEX monitoring_stations_active_idx ON core.monitoring_stations (is_active);
CREATE INDEX monitoring_stations_type_idx ON core.monitoring_stations (station_type);
CREATE INDEX ix_core_monitoring_stations_station_type ON core.monitoring_stations (station_type);

CREATE TABLE core.sensor_deployments (
	deployment_id SERIAL NOT NULL, 
	sensor_id INTEGER NOT NULL, 
	station_id INTEGER NOT NULL, 
	depth_cm FLOAT, 
	position_code TEXT, 
	resolution core.resolution_type, 
	installed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	removed_at TIMESTAMP WITH TIME ZONE, 
	status core.deployment_status NOT NULL, 
	notes TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	uuid UUID NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_by TEXT, 
	updated_by TEXT, 
	PRIMARY KEY (deployment_id), 
	CONSTRAINT depth_nonneg CHECK (depth_cm IS NULL OR depth_cm >= 0), 
	FOREIGN KEY(sensor_id) REFERENCES core.sensors (sensor_id), 
	FOREIGN KEY(station_id) REFERENCES core.monitoring_stations (station_id), 
	UNIQUE (uuid)
);

CREATE INDEX ix_core_sensor_deployments_station_id ON core.sensor_deployments (station_id);
CREATE INDEX ix_core_sensor_deployments_status ON core.sensor_deployments (status);
CREATE INDEX ix_core_sensor_deployments_depth_cm ON core.sensor_deployments (depth_cm);
CREATE INDEX ix_core_sensor_deployments_resolution ON core.sensor_deployments (resolution);
CREATE INDEX deployments_station_idx ON core.sensor_deployments (station_id);
CREATE INDEX deploy_active_idx ON core.sensor_deployments (sensor_id, removed_at);
CREATE INDEX ix_core_sensor_deployments_sensor_id ON core.sensor_deployments (sensor_id);
CREATE INDEX deployments_status_idx ON core.sensor_deployments (status);

CREATE TABLE core.deployment_date_changes (
	deployment_date_change_id SERIAL NOT NULL, 
	deployment_id INTEGER NOT NULL, 
	changed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	changed_by TEXT, 
	reason TEXT, 
	old_installed_at TIMESTAMP WITH TIME ZONE, 
	new_installed_at TIMESTAMP WITH TIME ZONE, 
	old_removed_at TIMESTAMP WITH TIME ZONE, 
	new_removed_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	uuid UUID NOT NULL, 
	PRIMARY KEY (deployment_date_change_id), 
	FOREIGN KEY(deployment_id) REFERENCES core.sensor_deployments (deployment_id), 
	UNIQUE (uuid)
);

CREATE INDEX deployment_date_changes_deployment_idx ON core.deployment_date_changes (deployment_id, changed_at);
CREATE INDEX ix_core_deployment_date_changes_deployment_id ON core.deployment_date_changes (deployment_id);

CREATE TABLE core.measurements (
	measurement_id BIGSERIAL NOT NULL, 
	deployment_id INTEGER NOT NULL, 
	variable_id INTEGER NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	source_value FLOAT, 
	flag_id INTEGER, 
	qc_status TEXT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (measurement_id), 
	CONSTRAINT measurements_unique_deployment_variable_ts UNIQUE (deployment_id, variable_id, ts), 
	FOREIGN KEY(deployment_id) REFERENCES core.sensor_deployments (deployment_id), 
	FOREIGN KEY(variable_id) REFERENCES core.variables (variable_id), 
	FOREIGN KEY(flag_id) REFERENCES meta.quality_flags (flag_id)
);

CREATE INDEX ix_core_measurements_variable_id ON core.measurements (variable_id);
CREATE INDEX ix_core_measurements_flag_id ON core.measurements (flag_id);
CREATE INDEX measurements_flag_idx ON core.measurements (flag_id);
CREATE INDEX measurements_qc_status_idx ON core.measurements (qc_status);
CREATE INDEX measurements_deploy_ts_idx ON core.measurements (deployment_id, ts DESC);
CREATE INDEX ix_core_measurements_ts ON core.measurements (ts);
CREATE INDEX ix_core_measurements_qc_status ON core.measurements (qc_status);
CREATE INDEX ix_core_measurements_deployment_id ON core.measurements (deployment_id);
CREATE INDEX measurements_variable_idx ON core.measurements (variable_id);

CREATE TABLE core.sensor_calibrations (
	calibration_id SERIAL NOT NULL, 
	deployment_id INTEGER NOT NULL, 
	variable_id INTEGER, 
	calibration_ts TIMESTAMP WITH TIME ZONE NOT NULL, 
	k_factor FLOAT, 
	offset_val FLOAT, 
	valid_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	valid_to TIMESTAMP WITH TIME ZONE, 
	performed_by TEXT, 
	notes TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	uuid UUID NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_by TEXT, 
	updated_by TEXT, 
	PRIMARY KEY (calibration_id), 
	FOREIGN KEY(deployment_id) REFERENCES core.sensor_deployments (deployment_id), 
	FOREIGN KEY(variable_id) REFERENCES core.variables (variable_id), 
	UNIQUE (uuid)
);

CREATE INDEX calibrations_deploy_ts_idx ON core.sensor_calibrations (deployment_id, calibration_ts DESC);
CREATE INDEX ix_core_sensor_calibrations_deployment_id ON core.sensor_calibrations (deployment_id);
CREATE INDEX ix_core_sensor_calibrations_variable_id ON core.sensor_calibrations (variable_id);

CREATE TABLE core.upload_row_issues (
	issue_id BIGSERIAL NOT NULL, 
	upload_id BIGINT NOT NULL, 
	deployment_id INTEGER, 
	variable_id INTEGER, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	incoming_value FLOAT, 
	existing_value FLOAT, 
	issue_type TEXT NOT NULL, 
	message TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (issue_id), 
	FOREIGN KEY(upload_id) REFERENCES core.uploads (upload_id) ON DELETE CASCADE, 
	FOREIGN KEY(deployment_id) REFERENCES core.sensor_deployments (deployment_id), 
	FOREIGN KEY(variable_id) REFERENCES core.variables (variable_id)
);

CREATE INDEX ix_core_upload_row_issues_ts ON core.upload_row_issues (ts);
CREATE INDEX ix_core_upload_row_issues_upload_id ON core.upload_row_issues (upload_id);
CREATE INDEX ix_core_upload_row_issues_variable_id ON core.upload_row_issues (variable_id);
CREATE INDEX ix_core_upload_row_issues_issue_type ON core.upload_row_issues (issue_type);
CREATE INDEX upload_row_issues_upload_idx ON core.upload_row_issues (upload_id, issue_type);
CREATE INDEX ix_core_upload_row_issues_deployment_id ON core.upload_row_issues (deployment_id);

CREATE TABLE core.derived_measurements (
	derived_measurement_id BIGSERIAL NOT NULL, 
	source_measurement_id BIGINT NOT NULL, 
	deployment_id INTEGER NOT NULL, 
	source_variable_id INTEGER NOT NULL, 
	derived_variable_id INTEGER NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	value FLOAT NOT NULL, 
	derivation_type TEXT NOT NULL, 
	calibration_id INTEGER, 
	calculation_run_id BIGINT, 
	flag_id INTEGER, 
	qc_status TEXT NOT NULL, 
	is_current BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (derived_measurement_id), 
	FOREIGN KEY(source_measurement_id) REFERENCES core.measurements (measurement_id), 
	FOREIGN KEY(deployment_id) REFERENCES core.sensor_deployments (deployment_id), 
	FOREIGN KEY(source_variable_id) REFERENCES core.variables (variable_id), 
	FOREIGN KEY(derived_variable_id) REFERENCES core.variables (variable_id), 
	FOREIGN KEY(calibration_id) REFERENCES core.sensor_calibrations (calibration_id), 
	FOREIGN KEY(calculation_run_id) REFERENCES core.calculation_runs (calculation_run_id), 
	FOREIGN KEY(flag_id) REFERENCES meta.quality_flags (flag_id)
);

CREATE INDEX ix_core_derived_measurements_calibration_id ON core.derived_measurements (calibration_id);
CREATE INDEX ix_core_derived_measurements_derived_variable_id ON core.derived_measurements (derived_variable_id);
CREATE INDEX ix_core_derived_measurements_qc_status ON core.derived_measurements (qc_status);
CREATE INDEX derived_measurements_status_idx ON core.derived_measurements (qc_status);
CREATE INDEX derived_measurements_source_idx ON core.derived_measurements (source_measurement_id);
CREATE INDEX derived_measurements_deploy_var_ts_idx ON core.derived_measurements (deployment_id, derived_variable_id, ts DESC);
CREATE INDEX ix_core_derived_measurements_source_variable_id ON core.derived_measurements (source_variable_id);
CREATE INDEX ix_core_derived_measurements_flag_id ON core.derived_measurements (flag_id);
CREATE INDEX ix_core_derived_measurements_deployment_id ON core.derived_measurements (deployment_id);
CREATE INDEX ix_core_derived_measurements_ts ON core.derived_measurements (ts);
CREATE INDEX ix_core_derived_measurements_is_current ON core.derived_measurements (is_current);
CREATE INDEX ix_core_derived_measurements_calculation_run_id ON core.derived_measurements (calculation_run_id);
CREATE INDEX ix_core_derived_measurements_source_measurement_id ON core.derived_measurements (source_measurement_id);

CREATE TABLE core.measurement_value_changes (
	measurement_value_change_id BIGSERIAL NOT NULL, 
	measurement_id BIGINT NOT NULL, 
	old_source_value FLOAT, 
	new_source_value FLOAT NOT NULL, 
	reason TEXT NOT NULL, 
	edited_by TEXT, 
	edited_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (measurement_value_change_id), 
	FOREIGN KEY(measurement_id) REFERENCES core.measurements (measurement_id) ON DELETE RESTRICT
);

CREATE INDEX ix_core_measurement_value_changes_edited_at ON core.measurement_value_changes (edited_at);
CREATE INDEX ix_core_measurement_value_changes_measurement_id ON core.measurement_value_changes (measurement_id);
CREATE INDEX measurement_value_changes_measurement_idx ON core.measurement_value_changes (measurement_id, edited_at);
