"""Regenerate migrations/baseline/000_baseline_schema.sql from the ORM models.

Run this whenever monitorforge_core.models changes and the baseline should
reflect it:

    .venv/Scripts/python.exe scripts/generate_baseline_sql.py

This is the file new projects copy in as their first migration (see
monitorforge-template). Projects that have already launched do NOT re-copy
this file when core's schema changes -- per the workspace rule that
"applied migrations are immutable" rule, they get a new incremental
migration for the delta instead. Only pre-launch/new projects take an
updated baseline.
"""

from pathlib import Path

from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql.named_types import ENUM, CreateEnumType
from sqlalchemy.schema import CreateIndex, CreateTable

from monitorforge_core.db import db
from monitorforge_core import models  # noqa: F401  (registers models with db)

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "src" / "monitorforge_core" / "migrations" / "baseline" / "000_baseline_schema.sql"


def generate_sql() -> str:
    """Compile CREATE TABLE/INDEX DDL for every model, no live DB connection needed."""
    dialect = postgresql.dialect()
    lines = [
        "-- Generated by scripts/generate_baseline_sql.py from monitorforge_core.models.",
        "-- Do not hand-edit. Re-run the generator instead.",
        "",
        "CREATE SCHEMA IF NOT EXISTS core;",
        "CREATE SCHEMA IF NOT EXISTS meta;",
        "",
    ]

    seen_enum_names: set[str] = set()
    for table in db.metadata.sorted_tables:
        for column in table.columns:
            if isinstance(column.type, ENUM) and column.type.name not in seen_enum_names:
                seen_enum_names.add(column.type.name)
                enum_ddl = str(CreateEnumType(column.type).compile(dialect=dialect)).strip()
                if not enum_ddl.endswith(";"):
                    enum_ddl += ";"
                lines.append(enum_ddl)
                lines.append("")

    for table in db.metadata.sorted_tables:
        ddl = str(CreateTable(table).compile(dialect=dialect)).strip()
        if not ddl.endswith(";"):
            ddl += ";"
        lines.append(ddl)
        lines.append("")

        for index in table.indexes:
            index_ddl = str(CreateIndex(index).compile(dialect=dialect)).strip()
            if not index_ddl.endswith(";"):
                index_ddl += ";"
            lines.append(index_ddl)
        if table.indexes:
            lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    sql = generate_sql()
    OUTPUT_PATH.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
